# Generated by Django 2.2.28 on 2023-03-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('ProfilePicture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=20)),
                ('CoverPicture', models.ImageField(upload_to='')),
                ('AddedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='what_the_book.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('ProfilePicture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('MainText', models.TextField()),
                ('CreatedOn', models.DateField()),
                ('Likes', models.IntegerField(default=0)),
                ('CreatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='what_the_book.User')),
                ('ReviewOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='what_the_book.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookToRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=20)),
                ('ReadBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='what_the_book.Admin')),
                ('RequestedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='what_the_book.User')),
            ],
            options={
                'verbose_name_plural': 'Requested books',
            },
        ),
    ]
