# Generated by Django 4.1.7 on 2023-03-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_the_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'users'},
        ),
    ]
