# Generated by Django 4.1.7 on 2023-03-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_the_book', '0003_rename_password_admin_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktorequest',
            options={'verbose_name_plural': 'requested books'},
        ),
    ]
