# Generated by Django 4.1.7 on 2023-03-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_the_book', '0004_alter_booktorequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
