# Generated by Django 2.2.28 on 2023-03-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_the_book', '0005_review_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverPicture',
            field=models.ImageField(blank=True, upload_to='images/book_covers/'),
        ),
    ]
