# Generated by Django 2.2.28 on 2023-03-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_the_book', '0006_auto_20230308_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
