# Generated by Django 2.2.28 on 2023-03-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_the_book', '0008_remove_review_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='slug',
            new_name='bookSlug',
        ),
    ]
