# Generated by Django 2.2.28 on 2023-03-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_the_book', '0009_auto_20230313_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookSlug',
        ),
    ]
