# Generated by Django 2.2.28 on 2023-03-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_the_book', '0010_remove_book_bookslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
